services:
  cloudflare-ddns-updater:
    build: .
    container_name: cloudflare-ddns-updater
    env_file: .env
    # Comment out the following two lines if logs are not needed
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
